
title: Dev Aspects
description: Nady Habashy's Homepage
show_github: true
show_downloads: false
theme: jekyll-theme-architect

github:
   #repository_url: http://devaspects.com
   #repository_name: devaspects
   owner_url: http://nady.habashy.de
   owner_name: Nady Habashy
